//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    
    public enum EnumFilterAuswertung : byte
    {
        Allgemein = 0,
        Arbeitszeit = 1,
        Anmeldung = 2,
        Bauteil = 3,
        Reparatur = 4,
        ArbeitszeitAuswertung = 5
    }
}
