//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    
    public enum EnumReperaturEreigniss : byte
    {
        Wartung_geplant = 0,
        Wartung_ungeplant = 1,
        Reparatur_geplant = 2,
        Reparatur_ungeplant = 3,
        Stillegung = 4
    }
}
