//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    
    public enum EnumStatusProtkoll : byte
    {
        Offen = 0,
        InBearbeitung = 1,
        Erledigt = 2,
        Abbruch = 3,
        GeneralAbbruch = 4
    }
}
