//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabAuswertung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabAuswertung()
        {
            this.DatenAbgleich = new DatenAbgleich();
        }
    
        public System.Guid Id { get; set; }
        public string ReportName { get; set; }
        public string ErstelltName { get; set; }
        public System.DateTime ErstelltDatum { get; set; }
        public string GeaendertName { get; set; }
        public System.DateTime GeaendertDatum { get; set; }
        public byte[] Report { get; set; }
        public string Bemerkung { get; set; }
    
        public DatenAbgleich DatenAbgleich { get; set; }
    }
}
