//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabArbeitszeitTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabArbeitszeitTag()
        {
            this.Krank = false;
            this.Urlaub = false;
            this.Feiertag = false;
            this.sArbeitszeiten = new HashSet<tabArbeitszeit>();
            this.DatenAbgleich = new DatenAbgleich();
        }
    
        public System.Guid Id { get; set; }
        public byte Tag { get; set; }
        public System.TimeSpan Zeit { get; set; }
        public System.TimeSpan ZeitKorrektur { get; set; }
        public System.TimeSpan Pause { get; set; }
        public bool Krank { get; set; }
        public bool Urlaub { get; set; }
        public bool Feiertag { get; set; }
        public System.TimeSpan Ueberstunden { get; set; }
        public System.TimeSpan Nachtschicht { get; set; }
        public System.TimeSpan NachschichtKorrektur { get; set; }
        public string Bemerkung { get; set; }
        public System.Guid fArbeitszeitAuswertung { get; set; }
    
        public DatenAbgleich DatenAbgleich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabArbeitszeit> sArbeitszeiten { get; set; }
        public virtual tabArbeitszeitAuswertung eArbeitszeitAuswertung { get; set; }
    }
}
