//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabArbeitszeitTerminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabArbeitszeitTerminal()
        {
            this.DatenAbgleich = new DatenAbgleich();
        }
    
        public System.Guid Id { get; set; }
        public string Bezeichnung { get; set; }
        public string IpNummer { get; set; }
        public int PortNummer { get; set; }
        public bool UpdateTerminal { get; set; }
        public short AnzahlFehler { get; set; }
        public System.Guid fStandort { get; set; }
    
        public DatenAbgleich DatenAbgleich { get; set; }
    
        public virtual tabStandort eStandort { get; set; }
    }
}
