//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabArbeitszeitAuswertung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabArbeitszeitAuswertung()
        {
            this.Urlaub = 0;
            this.Krank = 0;
            this.sArbeitszeitenTag = new HashSet<tabArbeitszeitTag>();
            this.DatenAbgleich = new DatenAbgleich();
        }
    
        public System.Guid Id { get; set; }
        public short Jahr { get; set; }
        public byte Monat { get; set; }
        public string SollStunden { get; set; }
        public string Ueberstunden { get; set; }
        public string Nachtschichten { get; set; }
        public string Feiertage { get; set; }
        public short Urlaub { get; set; }
        public short Krank { get; set; }
        public string AuszahlungUeberstunden { get; set; }
        public string Bemerkung { get; set; }
        public EnumStatusArbeitszeitAuswertung Status { get; set; }
        public System.Guid fBediener { get; set; }
    
        public DatenAbgleich DatenAbgleich { get; set; }
    
        public virtual tabBediener eBediener { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabArbeitszeitTag> sArbeitszeitenTag { get; set; }
    }
}
