//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabMaschine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabMaschine()
        {
            this.PortNummer = -1;
            this.ScannerNummer = -1;
            this.VorgabeProStunde = 0m;
            this.sDaten = new HashSet<tabDaten>();
            this.sAnmeldungen = new HashSet<tabAnmeldung>();
            this.sReparaturen = new HashSet<tabReparatur>();
        }
    
        public System.Guid Id { get; set; }
        public string MaschinenName { get; set; }
        public EnumProtokollName ProtokollName { get; set; }
        public string MaschinenAdresse { get; set; }
        public int PortNummer { get; set; }
        public int ScannerNummer { get; set; }
        public string PfadDaten { get; set; }
        public string PfadBediener { get; set; }
        public string Bemerkung { get; set; }
        public EnumStatusMaschine Status { get; set; }
        public Nullable<decimal> VorgabeProStunde { get; set; }
        public System.Guid fStandort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabDaten> sDaten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabAnmeldung> sAnmeldungen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabReparatur> sReparaturen { get; set; }
        public virtual tabProtokoll eProtokoll { get; set; }
        public virtual tabStandort eStandort { get; set; }
    }
}
