//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProtokoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabProtokoll()
        {
            this.AnzahlDurchlauf = 0;
            this.FehlerVerbindungMaschine = 0;
            this.FehlerPfadZurMaschine = 0;
            this.FehlerDatenImport = 0;
            this.FehlerDatenSpeichern = 0;
            this.DatenAbgleich = new DatenAbgleich();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime AuswertungStart { get; set; }
        public Nullable<System.DateTime> AuswertungEnde { get; set; }
        public System.DateTime LetztePositionDatum { get; set; }
        public System.DateTime LetzteDateiDatum { get; set; }
        public string ProtokollText { get; set; }
        public EnumStatusProtkoll Status { get; set; }
        public byte AnzahlDurchlauf { get; set; }
        public int FehlerVerbindungMaschine { get; set; }
        public int FehlerPfadZurMaschine { get; set; }
        public int FehlerDatenImport { get; set; }
        public int FehlerDatenSpeichern { get; set; }
    
        public DatenAbgleich DatenAbgleich { get; set; }
    
        public virtual tabMaschine eMaschine { get; set; }
    }
}
