//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JgMaschineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabReparatur
    {
        public System.Guid Id { get; set; }
        public string ProtokollText { get; set; }
        public EnumReperaturEreigniss Ereigniss { get; set; }
        public System.DateTime ReparaturVon { get; set; }
        public System.DateTime ReparaturBis { get; set; }
        public System.Guid fMaschine { get; set; }
        public System.Guid fVerursacher { get; set; }
        public System.Guid fProtokollant { get; set; }
        public bool InBearbeitung { get; set; }
    
        public virtual tabBediener eVerursacher { get; set; }
        public virtual tabBediener eProtokollant { get; set; }
        public virtual tabMaschine eMaschine { get; set; }
    }
}
